import { focalLengthToFovDeg } from './camera-math';
import type { Project } from './types';

/** 内置示例项目：演示层级、基础几何体、灯光、50mm 摄像机与动画轨道（16:9 画幅）。 */
export function createSampleProject(uri = 'lumora://sample-project', name = '示例项目'): Project {
  const now = new Date().toISOString();
  return {
    uri,
    name,
    schemaVersion: 4,
    createdAt: now,
    revision: 0,
    settings: { fps: 24, aspect: [16, 9] },
    activeSceneId: 'scene-1',
    scenes: [{ id: 'scene-1', name: '主场景', rootObjectIds: ['sample-group', 'sample-ground', 'sample-light', 'sample-camera', 'sample-camera-2'], activeCameraId: 'sample-camera' }],
    objects: [
      {
        id: 'sample-group',
        type: 'group',
        name: '场景对象',
        parentId: null,
        transform: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        visible: true,
        locked: false,
      },
      {
        id: 'sample-cube',
        type: 'primitive',
        name: '立方体',
        parentId: 'sample-group',
        transform: { position: [-2.5, 0.5, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        visible: true,
        locked: false,
        geometry: { kind: 'box' },
        material: { color: '#ff6b6b' },
      },
      {
        id: 'sample-sphere',
        type: 'primitive',
        name: '球体',
        parentId: 'sample-group',
        transform: { position: [0, 0.6, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        visible: true,
        locked: false,
        geometry: { kind: 'sphere' },
        material: { color: '#4dabf7' },
      },
      {
        id: 'sample-cone',
        type: 'primitive',
        name: '圆锥',
        parentId: 'sample-group',
        transform: { position: [2.5, 0.5, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        visible: true,
        locked: false,
        geometry: { kind: 'cone' },
        material: { color: '#69db7c' },
      },
      {
        id: 'sample-ground',
        type: 'primitive',
        name: '地面',
        parentId: null,
        transform: { position: [0, 0, 0], rotation: [-Math.PI / 2, 0, 0], scale: [12, 12, 1] },
        visible: true,
        locked: false,
        geometry: { kind: 'plane' },
        material: { color: '#232734' },
      },
      {
        id: 'sample-light',
        type: 'light',
        name: '主光',
        parentId: null,
        transform: { position: [4, 8, 4], rotation: [0, 0, 0], scale: [1, 1, 1] },
        visible: true,
        locked: false,
        light: { kind: 'directional', color: '#ffffff', intensity: 1.4 },
      },
      {
        id: 'sample-camera',
        type: 'camera',
        name: '主摄像机',
        parentId: null,
        transform: { position: [0, 2.6, 7], rotation: [0, 0, 0], scale: [1, 1, 1] },
        visible: true,
        locked: false,
        camera: {
          projection: 'perspective',
          focalLength: 50,
          fov: focalLengthToFovDeg(50),
          sensorWidth: 36,
          sensorHeight: 24,
          near: 0.1,
          far: 200,
          aspect: null,
        },
      },
      {
        id: 'sample-camera-2',
        type: 'camera',
        name: '俯拍机位',
        parentId: null,
        transform: { position: [6, 8, 4], rotation: [0, 0, 0], scale: [1, 1, 1] },
        visible: true,
        locked: false,
        camera: {
          projection: 'perspective',
          focalLength: 50,
          fov: focalLengthToFovDeg(50),
          sensorWidth: 36,
          sensorHeight: 24,
          near: 0.1,
          far: 200,
          aspect: null,
        },
      },
    ],
    tracks: [
      {
        id: 'sample-track-camera-dolly',
        name: '主摄像机推镜',
        objectId: 'sample-camera',
        targetPath: 'position',
        keyframes: [
          { time: 0, value: [0, 2.6, 7] },
          { time: 2, value: [0, 2.6, 4.5], interpolation: 'smooth' },
          { time: 4, value: [0, 2.6, 3], interpolation: 'smooth' },
        ],
      },
      {
        id: 'sample-track-cube-spin',
        name: '立方体旋转',
        objectId: 'sample-cube',
        targetPath: 'rotation',
        keyframes: [
          { time: 0, value: [0, 0, 0] },
          { time: 2, value: [0, Math.PI, 0] },
          { time: 4, value: [0, Math.PI * 2, 0] },
        ],
      },
      {
        id: 'sample-track-camera-focus',
        name: '主摄像机变焦',
        objectId: 'sample-camera',
        targetPath: 'focalLength',
        keyframes: [
          { time: 0, value: 50 },
          { time: 4, value: 35, interpolation: 'smooth' },
        ],
      },
      {
        id: 'sample-track-cube-bounce',
        name: '立方体跳动（已禁用）',
        objectId: 'sample-cube',
        targetPath: 'position',
        disabled: true,
        keyframes: [
          { time: 0, value: [-2.5, 0.5, 0] },
          { time: 1, value: [-2.5, 1.5, 0], interpolation: 'step' },
          { time: 2, value: [-2.5, 0.5, 0], interpolation: 'step' },
        ],
      },
    ],
    shots: [
      { id: 'sample-shot-1', name: '分镜 1 · 开场全景', cameraObjectId: 'sample-camera', startTime: 0, endTime: 1.5 },
      { id: 'sample-shot-2', name: '分镜 2 · 推近主体', cameraObjectId: 'sample-camera-2', startTime: 1.5, endTime: 3 },
      { id: 'sample-shot-3', name: '分镜 3 · 特写', cameraObjectId: 'sample-camera-2', startTime: 3, endTime: 4.5 },
    ],
    assets: [],
  };
}
